### ISSUE TITLE
Mailspring won't open after installing a theme

### ISSUE THREAD

**Issue by kpalczewski** [Foundry376/Mailspring-Theme-Starter#1]
Hi,

I downloaded this repo. I have Added a name, display name, title, and description for my theme to package.json, and changed the directory name to match.

Opened N1 and install the theme by going to Mailspring > Install New Theme... and selecting the directory.

Choose Developer > Run With Debug Flags for easier debugging.

Now my client won't open. In console I have error:
ln: failed to create symbolic link '/myhomefolder/snap/mailspring/209/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 247ms

{"error":null}

In mailspring's windows I have error:
Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('theme-Dark Blue') contains HTML space characters, which are not valid in tokens.
    at ThemeManager.activateThemePackage (/src/theme-manager.es6:135:29)
    at new AppEnvConstructor (/src/app-env.es6:95:17)
    at Object.<anonymous> (/src/secondary-window-bootstrap.es6:18:17)
    at Object.<anonymous> (/src/secondary-window-bootstrap.es6:26:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at setupWindow (file:///snap/mailspring/209/usr/share/mailspring/resources/app.asar/static/index.js:47:3)
    at window.onload (file:///snap/mailspring/209/usr/share/mailspring/resources/app.asar/static/index.js:75:5)

Can you please help me fix this issue?

**Comment by toxicmender** [comment]
The Hints are there:

`ln: failed to create symbolic link '/myhomefolder/snap/mailspring/209/.config/gtk-2.0/gtkfilechooser.ini': File exists`

try renaming the original symbolic link with .bak extension (ie; abc.ini to abc.ini.bak)

`Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('theme-Dark Blue') contains HTML space characters, which are not valid in tokens.`

try renaming the theme name to theme-Dark_Blue, essentially getting rid of space, you may use any character instead of space `_` is just what's used as convention

**Comment by Foundry376** [comment]
Hey folks thanks for reporting this - I'll see if I can fix the way
Mailspring handles this in the next update so this isn't an issue.

Ben

**Comment by bengotow** [comment]
Hey! This should be resolved by https://github.com/Foundry376/Mailspring/commit/5ae7e205147fde43ac75fc31d677bb110c0bd929 - the app will display an error if your theme's styles can't be compiled and offer to reset to the default theme.

**Comment by kpalczewski** [comment]
awesome! thank you!
